### ISSUE TITLE
ADCIRC tag for NOAA 2023 upgrade

### ISSUE THREAD

**Issue by gseroka** [adcirc/adcirc#349]
@zcobell @yujifunakoshiNOAA @ps2epsi @jwesterink @dylnwood @cblakely97 @poseidonND @saeed-moghimi-noaa 
All,

We will need to tag the ADCIRC code for the NOAA STOFS-2D-Global 2023 upgrade, similar to how we did for last year's NOAA STOFS-2D-Global 2022 upgrade: https://github.com/adcirc/adcirc/issues/315

@dylnwood is merging Coleman's @cblakely97 code https://github.com/cblakely97/adcirc into adcirc dev branch.

Then, we will tag as "noaa.stofs.2d.glo.v2.0.0r1".

This is the issue to start the work/conversation on this. 

Thanks,
@gseroka

**Comment by gseroka** [comment]
@dwirasae @jwesterink NCO wants two things updated:

1. remove warning messages during ADCIRC compilation (from METIS and other things): 
[build-all.txt](https://github.com/adcirc/adcirc/files/13602931/build-all.txt)
2. remove "dev" from ADCIRC version "v56.dev" tagged: something like "v56.00" (won't put "dev" into production)

then can tag as "noaa.stofs.2d.glo.v2.0.0r2"

**Comment by gseroka** [comment]
Thanks @zcobell. What is the version of ADCIRC within tag "noaa.stofs.2d.glo.v2.1.0r1"? So the below isn't correct?

The tag of adcirc is "noaa.stofs.2d.glo.v2.1.0r1", and the version of adcirc is "56.dev".

Thanks for the feedback in the warnings, understood.

**Comment by zcobell** [comment]
Try running the following:

```shell
$ git checkout noaa.stofs.2d.glo.v2.1.0r1
$ git describe --always --tags
noaa.stofs.2d.glo.v2.1.0r1
```

The output of `git describe` is the what we consider the version when the difference from a tag is zero. The `exportAdcirc.sh` script writes the `version.F` when the code is exported. There is a file contained in the repository called `version_default.F` for when folks don't export the code properly and is essentially a fallback. When working from a git repository and building the code, the `adcircVersion.sh` script runs as part of the build process to generate `version.F`. 

```shell
cd scripts
./exportAdcirc.sh
```

After running the `exportAdcirc.sh` script to produce a packaged version of the code, the package contains a true `version.F` file, which for your tag looks like this:

```fortran
module version
character(80), parameter :: ADC_VERSION = "noaa.stofs.2d.glo.v2.1.0r1"
character(80), parameter :: ADC_HASH    = "c359f1a4a7a441a88bfb17ede43827487ed567fa"
integer, save       :: FileFmtMajor = 1
integer, save       :: FileFmtMinor = 2
integer, save       :: FileFmtRev   = 0
end module version
```

The variable `ADC_VERSION` is what is displayed when the code runs. More importantly (in my mind) is that the code now has `ADC_HASH` embedded, which is the definitive marker in the git repository. 

Internally, we use the `v56.dev` marker to help track when the development of v56 began. 

Way back when (#315), we settled on using a NOAA specific tag rather than forcing out integer ADCIRC releases, so I think it is just somewhat of a process update to ensure that you get the right embedded metadata associated with the NOAA releases.

**Comment by zcobell** [comment]
`version_default.F` is not used by the code, and is deleted before the code is packaged for distribution. Attached is the output from running the export script to create a distributable package. 

[adcirc_noaa.stofs.2d.glo.v2.1.0r1.tar.gz](https://github.com/adcirc/adcirc/files/13606330/adcirc_noaa.stofs.2d.glo.v2.1.0r1.tar.gz)

**Comment by zcobell** [comment]
Code is tagged and available here:

https://github.com/adcirc/adcirc/releases/tag/noaa.stofs.2d.glo.v2.1.0r1

**Comment by gseroka** [comment]
Meeting with NCO 03/07/2024 Notes
- last release for adcirc was v55.02; for NOAA WCOSS2 /apps, used v55.10, then v55.11, then v55.12 
- WCOSS2 /apps versions (e.g. for adcirc) will have no more than 3 versions available (i.e. not all applications will have to update immediately to the latest version)
- adcirc hopes to release more frequently (e.g. every 6 months)- hopefully resolves a lot of issues (e.g. so each major upgrade doesn't batch so many things together)
